spring:
  datasource:
    url: jdbc:mysql://localhost:3306/echannelling_client?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: shanuka1234
    port: 25
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
        transport:
          protocol: smtp
    username: futuresoftcus@gmail.com

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin


