spring:
  datasource:
    url: jdbc:mysql://mysql-category:3306/echannelling_category?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://oauth_service/oauth/check_token
#    client:
#      client-id: mobile
#      client-secret: pin
